### ISSUE TITLE
Error occurs when requesting images with a width greater than 1024 pixels

### ISSUE THREAD

**Issue by moon90175** [bedovyy/ComfyUI_NAIDGenerator#18]
Hello, I recently discovered that when requesting images with a width greater than 1024 pixels, their metadata becomes corrupted. When I try to read the metadata using PNG info, I get the error message: 'Error -3 while decompressing data: invalid distance too far back. Compressed file ended before the end-of-stream marker was reached'. Then, the metadata I'm able to read is all jumbled text. Interestingly, everything works normally as long as the image width is less than 1024 pixels. If there's a way to fix this, I would be very grateful.

**Comment by moon90175** [comment]
To further clarify, the image metadata is normal in NAI_autosave, but the error occurs after going through ComfyUI's built-in save_image function, which is when the image metadata becomes corrupted. Moreover, this error only happens with images wider than 1024 pixels.

**Comment by bedovyy** [comment]
I am not sure about that, because NAI_autosave has exif info and png by built-in `Save Image` node has ComfyUI workflow.
(It still has metadata in stealth png info, but PNG info on Forge just shows ComfyUI workflow, and that why I keep original image as NAI_autosave)

Which PNG info did you use? Could you provide corruped image here or bedovyy@gmail.com?

**Comment by moon90175** [comment]
I just tried again and found that the problem resolved itself! It's very likely that the issue was unrelated to the plugin and was instead a connection problem. Thank you for your response!
